### ISSUE TITLE
Complete datathinking.org/university-of-tartu/getting-started checklist

### ISSUE THREAD

**Issue by jaanli** [onefact/datathinking.org#3]
- [x] Read datathinking.org/university-of-tartu/getting-started
- [x] Install VS Code
- [x] Get GitHub student education pack
- [x] Ask any questions outstanding by the end of this checklist in this issue by leaving a comment below with what you tried and where you are stuck.

**Comment by altosaar** [comment]
I'm stuck on installing VS Code, please help.
